version: "3"

services:
  db:
    container_name: container_postgres
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: teste_rd
